apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gdbot
  template:
    metadata:
      labels:
        app: gdbot
    spec:
      containers:
      - image: registry.cloud.okteto.net/dissipator/gdbot:14
        name: gdbot
        
apiVersion: v1
kind: Service
metadata:
  name: gdbot
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
  - name: "gdbot"
    port: 3000
  selector:
    app: gdbot
