apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
      - image: registry.cloud.okteto.net/dissipator/gdbot:v1.3
        name: dev
        
apiVersion: v1
kind: Service
metadata:
  name: dev
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
  - name: "dev"
    port: 3000
  selector:
    app: dev
